apps/index/urls.py
from django.urls import path, include, re_path
from .views import IndexView

app_name = 'index'

urlpatterns = [
    # 首页
    path('', IndexView.as_view(), name='index'),
]

apps/info/urls.py
from django.urls import path, include, re_path
from .views import ArticleView, CategoryView, A_listView

app_name = 'info'

urlpatterns = [
    # 首页
    path('article/<int:article_id>', ArticleView.as_view(), name='article'),
    path('category/<int:category_id>', CategoryView.as_view(), name='category'),
    path('a_list', A_listView.as_view(), name='a_list'),
    # path('', ImgView.as_view(), name='img'),
]

uuu/urls.py
from django.urls import path, include
from django.conf import settings
import xadmin
from django.conf.urls.static import static

urlpatterns = [
    path('', include('index.urls', namespace="index")),
    path('', include('info.urls', namespace="article")),
    path('', include('info.urls', namespace="category")),
    path('', include('info.urls', namespace="a_list")),
    path('admin/', xadmin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/info/models.py
from django.db import models
from users.models import UserProfile
from ckeditor_uploader.fields import RichTextUploadingField


# 文章分类
class Category(models.Model):
    name = models.CharField('内容分类', max_length=100)
    color = models.CharField('分类颜色', max_length=100, default='#666666', blank=False)

    class Meta:
        verbose_name = '内容分类'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name


# 文章标签
class Tag(models.Model):
    name = models.CharField('文章标签', max_length=100)

    class Meta:
        verbose_name = '文章标签'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name


# 推荐位
class Tui(models.Model):
    name = models.CharField('推荐位', max_length=100)

    class Meta:
        verbose_name = '推荐位'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name


# 文章
class Article(models.Model):
    title = models.CharField('标题', max_length=70)
    excerpt = models.TextField('摘要', max_length=200, blank=True)
    category = models.ForeignKey(Category, on_delete=models.DO_NOTHING, verbose_name='分类', blank=True, null=True)
    # 使用外键关联分类表与分类是一对多关系
    tags = models.ManyToManyField(Tag, verbose_name='标签', blank=True)
    # 使用外键关联标签表与标签是多对多关系
    img = models.ImageField(upload_to='article_img/%Y/%m/%d/', verbose_name='文章图片', blank=True, null=True)
    body = RichTextUploadingField(verbose_name='文章详情')
    user = models.ForeignKey(UserProfile, on_delete=models.CASCADE, verbose_name='用户')
    """
    文章作者，这里User是从重构的users.models导入的。这里我们通过 ForeignKey 把文章和 User 关联了起来。
    """
    views = models.PositiveIntegerField('阅读量', default=0)
    tui = models.ForeignKey(Tui, on_delete=models.DO_NOTHING, verbose_name='推荐位', blank=True, null=True)
    created_time = models.DateTimeField('发布时间', auto_now_add=True)
    modified_time = models.DateTimeField('修改时间', auto_now=True)

    class Meta:
        verbose_name = '文章'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.title

apps/info/views.py
from django.shortcuts import render
from django.views.generic.base import View
from .models import Article, Tag, Category
from pure_pagination import Paginator, EmptyPage, PageNotAnInteger


class ArticleView(View):
    '''文章详情页'''

    def get(self, request, article_id):
        # 文章详情
        article = Article.objects.get(id=int(article_id))
        article.views += 1
        article.save()
        previous_article = Article.objects.filter(created_time__gt=article.created_time,
                                                  category=article.category.id).first()
        next_article = Article.objects.filter(created_time__lt=article.created_time,
                                              category=article.category.id).last()
        # 取出文章对应标签所有标签
        tags = article.tags.all()
        relate_articles = Article.objects.all().order_by('?')[0:10]
        # 旅游指南是多对多查询
        guide_articles = Article.objects.prefetch_related('tags').order_by('?')[:5]
        hot_articles = Article.objects.all().order_by('-views')[0:6]
        return render(request, 'article.html', {
            'article': article,
            'previous_article': previous_article,
            'next_article': next_article,
            'relate_articles': relate_articles,
            'guide_articles': guide_articles,
            'hot_articles': hot_articles,
            'tags': tags
        })


class CategoryView(View):
    '''文章分类页'''

    def get(self, request, category_id):
        category = Category.objects.get(id=int(category_id))
        category_articles = category.article_set.all()
        new_articles = category_articles.order_by('-modified_time')
        category_hot_articles = category_articles.order_by('-views')[0:5]
        category_guide_articles = category_articles.order_by('?')[0:6]
        category_articles_nums = category_articles.count()
        # 对新闻进行分页
        # 尝试获取前台get请求传递过来的page参数
        # 如果是不合法的配置参数默认返回第一页
        try:
            page = request.GET.get('page', 1)
        except PageNotAnInteger:
            page = 1
        # 这里指从category_articles中取10个出来，每页显示10个
        p = Paginator(new_articles, 10, request=request)
        category_all_articles = p.page(page)

        return render(request, 'category.html', {
            'category': category,
            'category_all_articles': category_all_articles,
            'category_hot_articles': category_hot_articles,
            'category_guide_articles': category_guide_articles,
        })


class A_listView(View):
    '''文章列表'''

    def get(self, request):
        hot_articles = Article.objects.all().order_by('-views')[0:10]
        guide_articles = Article.objects.order_by('-modified_time')[0:26]
        return render(request, 'a_list.html', {
            'hot_articles': hot_articles,
            'guide_articles': guide_articles,
        })

extra_apps/xadmin/views/base.py
import copy
import functools
import datetime
import decimal
from functools import update_wrapper
from inspect import getfullargspec

from django import forms
from django.apps import apps
from django.conf import settings
from django.contrib import messages
from django.contrib.auth import get_permission_codename
from django.core.exceptions import ValidationError
from django.core.serializers.json import DjangoJSONEncoder
from django.urls.base import reverse
from django.http import HttpResponse
from django.template import Context, Template
from django.template.response import TemplateResponse
from django.utils import six
from django.utils.decorators import method_decorator, classonlymethod
from django.utils.encoding import force_text, smart_text, smart_str
from django.utils.functional import Promise
from django.utils.http import urlencode
from django.utils.itercompat import is_iterable
from django.utils.safestring import mark_safe
from django.utils.text import capfirst
from django.utils.translation import ugettext as _
from django.views.decorators.csrf import csrf_protect
from django.views.generic import View
from collections import OrderedDict
from xadmin.util import static, json, vendor, sortkeypicker

from xadmin.models import Log

csrf_protect_m = method_decorator(csrf_protect)


class IncorrectPluginArg(Exception):
    pass


def get_content_type_for_model(obj):
    from django.contrib.contenttypes.models import ContentType
    return ContentType.objects.get_for_model(obj, for_concrete_model=False)


def filter_chain(filters, token, func, *args, **kwargs):
    if token == -1:
        return func()
    else:
        def _inner_method():
            fm = filters[token]
            fargs = getfullargspec(fm)[0]
            if len(fargs) == 1:
                # Only self arg
                result = func()
                if result is None:
                    return fm()
                else:
                    raise IncorrectPluginArg(u'Plugin filter method need a arg to receive parent method result.')
            else:
                return fm(func if fargs[1] == '__' else func(), *args, **kwargs)
        return filter_chain(filters, token - 1, _inner_method, *args, **kwargs)


def filter_hook(func):
    tag = func.__name__
    func.__doc__ = "``filter_hook``\n\n" + (func.__doc__ or "")

    @functools.wraps(func)
    def method(self, *args, **kwargs):

        def _inner_method():
            return func(self, *args, **kwargs)

        if self.plugins:
            filters = [(getattr(getattr(p, tag), 'priority', 10), getattr(p, tag))
                       for p in self.plugins if callable(getattr(p, tag, None))]
            filters = [f for p, f in sorted(filters, key=lambda x:x[0])]
            return filter_chain(filters, len(filters) - 1, _inner_method, *args, **kwargs)
        else:
            return _inner_method()
    return method


def inclusion_tag(file_name, context_class=Context, takes_context=False):
    def wrap(func):
        @functools.wraps(func)
        def method(self, context, nodes, *arg, **kwargs):
            _dict = func(self, context, nodes, *arg, **kwargs)
            from django.template.loader import get_template, select_template
            cls_str = str if six.PY3 else basestring
            if isinstance(file_name, Template):
                t = file_name
            elif not isinstance(file_name, cls_str) and is_iterable(file_name):
                t = select_template(file_name)
            else:
                t = get_template(file_name)

            _dict['autoescape'] = context.autoescape
            _dict['use_l10n'] = context.use_l10n
            _dict['use_tz'] = context.use_tz
            _dict['admin_view'] = context['admin_view']

            csrf_token = context.get('csrf_token', None)
            if csrf_token is not None:
                _dict['csrf_token'] = csrf_token
            nodes.append(t.render(_dict))

        return method
    return wrap


class JSONEncoder(DjangoJSONEncoder):

    def default(self, o):
        if isinstance(o, datetime.datetime):
            return o.strftime('%Y-%m-%d %H:%M:%S')
        elif isinstance(o, datetime.date):
            return o.strftime('%Y-%m-%d')
        elif isinstance(o, decimal.Decimal):
            return str(o)
        elif isinstance(o, Promise):
            return force_text(o)
        else:
            try:
                return super(JSONEncoder, self).default(o)
            except Exception:
                return smart_text(o)


class BaseAdminObject(object):

    def get_view(self, view_class, option_class=None, *args, **kwargs):
        opts = kwargs.pop('opts', {})
        return self.admin_site.get_view_class(view_class, option_class, **opts)(self.request, *args, **kwargs)

    def get_model_view(self, view_class, model, *args, **kwargs):
        return self.get_view(view_class, self.admin_site._registry.get(model), *args, **kwargs)

    def get_admin_url(self, name, *args, **kwargs):
        return reverse('%s:%s' % (self.admin_site.app_name, name), args=args, kwargs=kwargs)

    def get_model_url(self, model, name, *args, **kwargs):
        return reverse(
            '%s:%s_%s_%s' % (self.admin_site.app_name, model._meta.app_label,
                             model._meta.model_name, name),
            args=args, kwargs=kwargs, current_app=self.admin_site.name)

    def get_model_perm(self, model, name):
        return '%s.%s_%s' % (model._meta.app_label, name, model._meta.model_name)

    def has_model_perm(self, model, name, user=None):
        user = user or self.user
        return user.has_perm(self.get_model_perm(model, name)) or (name == 'view' and self.has_model_perm(model, 'change', user))

    def get_query_string(self, new_params=None, remove=None):
        if new_params is None:
            new_params = {}
        if remove is None:
            remove = []
        p = dict(self.request.GET.items()).copy()
        arr_keys = list(p.keys())
        for r in remove:
            for k in arr_keys:
                if k.startswith(r):
                    del p[k]
        for k, v in new_params.items():
            if v is None:
                if k in p:
                    del p[k]
            else:
                p[k] = v
        return '?%s' % urlencode(p)

    def get_form_params(self, new_params=None, remove=None):
        if new_params is None:
            new_params = {}
        if remove is None:
            remove = []
        p = dict(self.request.GET.items()).copy()
        arr_keys = list(p.keys())
        for r in remove:
            for k in arr_keys:
                if k.startswith(r):
                    del p[k]
        for k, v in new_params.items():
            if v is None:
                if k in p:
                    del p[k]
            else:
                p[k] = v
        return mark_safe(''.join(
            '<input type="hidden" name="%s" value="%s"/>' % (k, v) for k, v in p.items() if v))

    def render_response(self, content, response_type='json'):
        if response_type == 'json':
            response = HttpResponse(content_type="application/json; charset=UTF-8")
            response.write(
                json.dumps(content, cls=JSONEncoder, ensure_ascii=False))
            return response
        return HttpResponse(content)

    def template_response(self, template, context):
        return TemplateResponse(self.request, template, context)

    def message_user(self, message, level='info'):
        """
        Send a message to the user. The default implementation
        posts a message using the django.contrib.messages backend.
        """
        if hasattr(messages, level) and callable(getattr(messages, level)):
            getattr(messages, level)(self.request, message)

    def static(self, path):
        return static(path)

    def vendor(self, *tags):
        return vendor(*tags)

    def log(self, flag, message, obj=None):
        log = Log(
            user=self.user,
            ip_addr=self.request.META['REMOTE_ADDR'],
            action_flag=flag,
            message=message
        )
        if obj:
            log.content_type = get_content_type_for_model(obj)
            log.object_id = obj.pk
            log.object_repr = force_text(obj)
        log.save()


class BaseAdminPlugin(BaseAdminObject):

    def __init__(self, admin_view):
        self.admin_view = admin_view
        self.admin_site = admin_view.admin_site

        if hasattr(admin_view, 'model'):
            self.model = admin_view.model
            self.opts = admin_view.model._meta

    def init_request(self, *args, **kwargs):
        pass


class BaseAdminView(BaseAdminObject, View):
    """ Base Admin view, support some comm attrs."""

    base_template = 'xadmin/base.html'
    need_site_permission = True

    def __init__(self, request, *args, **kwargs):
        self.request = request
        self.request_method = request.method.lower()
        self.user = request.user

        self.base_plugins = [p(self) for p in getattr(self,
                                                      "plugin_classes", [])]

        self.args = args
        self.kwargs = kwargs
        self.init_plugin(*args, **kwargs)
        self.init_request(*args, **kwargs)

    @classonlymethod
    def as_view(cls):
        def view(request, *args, **kwargs):
            self = cls(request, *args, **kwargs)

            if hasattr(self, 'get') and not hasattr(self, 'head'):
                self.head = self.get

            if self.request_method in self.http_method_names:
                handler = getattr(
                    self, self.request_method, self.http_method_not_allowed)
            else:
                handler = self.http_method_not_allowed

            return handler(request, *args, **kwargs)

        # take name and docstring from class
        update_wrapper(view, cls, updated=())
        view.need_site_permission = cls.need_site_permission

        return view

templates/category.html
{% extends 'base.html' %}
{% load staticfiles %}
{#标题#}
{% block title %}{{ index_seo.title }}{% endblock %}
{#关键词#}
{% block keywords %}{{ index_seo.keywords }}{% endblock %}
{#描述#}
{% block description %}{{ index_seo.description }}{% endblock %}

{% block custom_css %}
{% endblock %}
{% block body_start %}
    <body class="style-games single-post bg-light">
{% endblock %}


{% block custom_bread %}
    <div class="container">
        <ul class="breadcrumbs">
            <li class="breadcrumbs__item">
                <a href="{% url 'index:index' %}" class="breadcrumbs__url">首页</a>
            </li>
            <li class="breadcrumbs__item">
                <a href="{% url 'category:category' category.id %}" class="breadcrumbs__url">{{ category.name }}</a>
            </li>
        </ul>
    </div>
{% endblock %}

{% block content %}

    <div class="main-container container" id="main-container">
        <!-- Content -->
        <div class="row">

            <!-- Posts -->
            <div class="col-lg-8 blog__content mb-72">
                <h1 class="page-title">{{ category.name }}</h1>

                <div class="row card-row">
                    {% for category_all_article in category_all_articles.object_list %}
                        <div class="col-md-6">
                            <article class="entry card">
                                <div class="entry__img-holder card__img-holder">
                                    <a href="{% url 'article:article' category_all_article.id %}">
                                        <div class="thumb-container thumb-70">
                                            <img data-src="{{ MEDIA_URL }}{{ category_all_article.img }}"
                                                 src="{% static 'img/empty.png' %}"
                                                 class="entry__img lazyload" alt=""/>
                                        </div>
                                    </a>
                                    {#                                    <a href="#"#}
                                    {#                                       class="entry__meta-category entry__meta-category--label entry__meta-category--align-in-corner entry__meta-category--violet">{{ category.name }}</a>#}
                                </div>

                                <div class="entry__body card__body">
                                    <div class="entry__header">

                                        <h2 class="entry__title">
                                            <a href="{% url 'article:article' category_all_article.id %}">{{ category_all_article.title }}</a>
                                        </h2>
                                        <ul class="entry__meta">
                                            <li class="entry__meta-author">
                                                <span>来自</span>
                                                <a href="#">{{ category_all_article.user.nick_name }}</a>
                                            </li>
                                            <li class="entry__meta-date">
                                                {{ category_all_article.modified_time }}
                                            </li>
                                        </ul>
                                    </div>
                                    <div class="entry__excerpt">
                                        <p>{{ category_all_article.excerpt|truncatechars:43 }}</p>
                                    </div>
                                </div>
                            </article>
                        </div>
                    {% endfor %}
                </div>

                <!-- Pagination -->
                <nav class="pagination">
                    {#                    <a href="{% url 'category:category' category.id %}" class="pagination__page">#}
                    {#                        <span class="pagination__page pagination__page--current">首页</span>#}
                    {#                    </a>#}
                    {% if category_all_articles.has_previous %}
                        <a href="?{{ category_all_articles.previous_page_number.querystring }}"
                           class="pagination__page">
                            <i class="ui-arrow-left"></i>
                        </a>
                    {% endif %}
                    {% for page in category_all_articles.pages %}
                        {% if page %}
                            {% ifequal page category_all_articles.number %}
                                <a href="?{{ page.querystring }}" class="pagination__page pagination__page--current">
                                    {{ page }}
                                </a>
                            {% else %}
                                <a href="?{{ page.querystring }}" class="pagination__page">{{ page }}</a>
                            {% endifequal %}
                        {% else %}
                            <a href="?{{ page.querystring }}" class="pagination__page">...</a>
                        {% endif %}
                    {% endfor %}
                    {% if category_all_articles.has_next %}
                        <a href="?{{ category_all_articles.next_page_number.querystring }}" class="pagination__page">
                            <i class="ui-arrow-right"></i>
                        </a>
                    {% endif %}
                </nav>
            </div> <!-- end posts -->

            <!-- Sidebar -->
            <aside class="col-lg-4 sidebar sidebar--right">

                <aside class="widget widget-review-posts">
                    <h4 class="widget-title">热门推荐</h4>
                    {% for category_hot_article in category_hot_articles %}
                        <article class="entry">
                            <div class="entry__img-holder">
                                <a href="{% url 'article:article' category_hot_article.id %}">
                                    <div class="thumb-container thumb-60">
                                        <img data-src="{{ MEDIA_URL }}{{ category_hot_article.img }}"
                                             src="{% static 'img/empty.png' %}"
                                             class="entry__img lazyload" alt="">
                                        <span class="entry-score">{{ category_hot_article.views }}</span>
                                    </div>
                                </a>
                            </div>

                            <div class="entry__body">
                                <div class="entry__header">
                                    <h2 class="entry__title">
                                        <a href="{% url 'article:article' category_hot_article.id %}">{{ category_hot_article.title }}</a>
                                    </h2>
                                    <ul class="entry__meta">
                                        <li class="entry__meta-author">
                                            <span>来自</span>
                                            <a href="#">{{ category_hot_article.user.nick_name }}</a>
                                        </li>
                                        <li class="entry__meta-date">
                                            {{ category_hot_article.modified_time }}
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </article>
                    {% endfor %}
                    <button class="btn btn-lg btn-light btn-wide load-more">
                        <span>查看更多 <i class="ui-arrow-down"></i></span>
                    </button>

                </aside> <!-- end widget reviews -->

                <!-- Widget Popular Posts -->
                <aside class="widget widget-popular-posts">
                    <h4 class="widget-title">相关指南</h4>
                    <ul class="post-list-small">
                        {% for category_guide_article in category_guide_articles %}
                            <li class="post-list-small__item">
                                <article class="post-list-small__entry clearfix">
                                    <div class="post-list-small__img-holder">
                                        <div class="thumb-container thumb-100">
                                            <a href="{% url 'article:article' category_guide_article.id %}">
                                                <img data-src="{{ MEDIA_URL }}{{ category_guide_article.img }}"
                                                     src="{% static 'img/empty.png' %}"
                                                     alt="" class=" lazyload">
                                            </a>
                                        </div>
                                    </div>
                                    <div class="post-list-small__body">
                                        <h3 class="post-list-small__entry-title">
                                            <a href="{% url 'article:article' category_guide_article.id %}">{{ category_guide_article.title }}</a>
                                        </h3>
                                        <ul class="entry__meta">
                                            <li class="entry__meta-author">
                                                <span>来自</span>
                                                <a href="#">{{ category_guide_article.user.nick_name }}</a>
                                            </li>
                                            <li class="entry__meta-date">
                                                {{ category_guide_article.modified_time }}
                                            </li>
                                        </ul>
                                    </div>
                                </article>
                            </li>
                        {% endfor %}
                    </ul>

                </aside> <!-- end widget popular posts -->

            </aside> <!-- end sidebar -->

        </div> <!-- end content -->
    </div> <!-- end main container -->

{% endblock %}
{% block custom_js %}
{% endblock %}
{% block body_end %}
    </body>
{% endblock %}